### ISSUE TITLE
Create a reproducible working environment and installation instructions

### ISSUE THREAD

**Issue by schae234** [LinkageIO/LocusPocus#2]
## Description

In order to mitigate differences between OS installs, differences in libraries, and to ensure a similar development environment, we should decide on a common working environment that we know LocusPocus will work in. 

In the past I have had success with python virtual environments (both virtualenv as well as conda). This will also double as the default way to run our CI tests, since the `.travis.yml` file will be a simple execution of the install script.
## Tasks
- [x] create an install script that creates a virtual environment for LocusPocus
  - [x] maybe use [miniconda](http://conda.pydata.org/miniconda.html)?
  - [x] update `.travis.yml` to use install script
  - [x] update README.md to show installation instructions
